name: Render PNGs

on:
  workflow_dispatch:
  
jobs:
  render:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install inkscape
        run: sudo apt-get install inkscape

      - name: Render pngs
        run: |
          mkdir -p pngs
          for image in "" black dark light white; do
            for size in 256 640 1080 2160; do
              inkscape \
                --export-width=${size} \
                --export-filename=pngs/parinfer-org-logo-${image}-${size}x${size}.png \
                --export-type=png \
                parinfer-org-logo-${image}.svg
     
      - name: Update repo
        run: |
          git add png
          git commit -m "Add/update png renders"
          git push
